### ISSUE TITLE
Home - Check superlative 

### ISSUE THREAD

**Issue by malejaps** [danielcb29/danielcb29.github.io#2]
In the sentence "Software Engineer passionate about writing code and implementing **latest** awesome technologies..." the word **latest** should be **the latest**

![thelatest](https://user-images.githubusercontent.com/9902912/27661117-c16d9e60-5c1e-11e7-82fe-34d413e2e11d.png)

**Comment by danielcb29** [comment]
Solved on #11 , check the result please 😎
