### ISSUE TITLE
Home/About me - Formal I'm

### ISSUE THREAD

**Issue by malejaps** [danielcb29/danielcb29.github.io#4]
This page is a personal presentation, if it is for job the text should be formal. 
Change I'm and write I am.

![iam](https://user-images.githubusercontent.com/9902912/27661793-4c8b527e-5c21-11e7-9450-1e7a2c0b566b.png)

![iam2](https://user-images.githubusercontent.com/9902912/27661815-6163c9d8-5c21-11e7-9193-1a0cc387b716.png)

![iam3](https://user-images.githubusercontent.com/9902912/27663448-f8c6fe84-5c27-11e7-824f-80365ff61e5d.png)

**Comment by danielcb29** [comment]
Solved, check last release
