### ISSUE TITLE
Footer - CV in Spanish - Error

### ISSUE THREAD

**Issue by malejaps** [danielcb29/danielcb29.github.io#5]
The PDF related to CV in Spanish is downloading CV in English. 

![cvspanish](https://user-images.githubusercontent.com/9902912/27663139-8b716aaa-5c26-11e7-9a9c-fad385109679.png)

![cvspanish2](https://user-images.githubusercontent.com/9902912/27663155-a1f56240-5c26-11e7-8b9c-d040b9babfe7.png)

**Comment by danielcb29** [comment]
I must update the spanish version 😅

**Comment by danielcb29** [comment]
You can check the new version now 😎
