### ISSUE TITLE
About me - Age, Nationality and Phone

### ISSUE THREAD

**Issue by malejaps** [danielcb29/danielcb29.github.io#6]
**Age**

Change 29 January 1994 to January, 29th 1994

![age](https://user-images.githubusercontent.com/9902912/27663185-bf691704-5c26-11e7-94a0-0e677ccba156.png)

**Nacionality**

Change Colombia to Colombian

![colombian](https://user-images.githubusercontent.com/9902912/27663189-c7ac0c0a-5c26-11e7-8066-ccea046bcac6.png)

Parentheses

Write the phone with perentheses (+57).....

![parentesis](https://user-images.githubusercontent.com/9902912/27663199-cf24c3b4-5c26-11e7-8294-205d888d44fd.png)

**Comment by danielcb29** [comment]
Solved on #11 , check the result please 😎
