### ISSUE TITLE
Send me a message - Doesn't work the button

### ISSUE THREAD

**Issue by malejaps** [danielcb29/danielcb29.github.io#8]
Doesn't work the button "Send me a message".

![sendmeamessage](https://user-images.githubusercontent.com/9902912/27663889-2753b326-5c2a-11e7-8943-a206370596aa.png)

**Comment by danielcb29** [comment]
For version 1.0 this button just change page to cantact page. 

@malejaps Do you prefer to open the mail service instead of change page?, or what could you suggest to improve this feature for this MVP?

**Comment by danielcb29** [comment]
Solved, check last release
